import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup, FormBuilder } from '@angular/forms';
import { DomSanitizer } from '@angular/platform-browser';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-hr',
  templateUrl: './hr.component.html',
  styleUrls: ['./hr.component.scss'],
})
export class HrComponent implements OnInit {
  data1: any = [];
  myForm: any = FormGroup;

  FormData: any =
    // {
    //   title: 'Ashu Form',
    //   description: '',
    //   labelPlacement: 'top_label',
    //   descriptionPlacement: 'below',
    //   button: {
    //     type: 'text',
    //     text: 'Submit',
    //     imageUrl: '',
    //     width: 'auto',
    //     location: 'bottom',
    //     layoutGridColumnSpan: 12,
    //     id: 'submit',
    //   },
    //   fields: [
    //     {
    //       type: 'text',
    //       id: 1,
    //       formId: 8,
    //       label: 'name',
    //       adminLabel: '',
    //       isRequired: false,
    //       size: 'large',
    //       errorMessage: '',
    //       visibility: 'visible',
    //       inputs: null,
    //       description: '',
    //       allowsPrepopulate: false,
    //       inputMask: false,
    //       inputMaskValue: '',
    //       inputMaskIsCustom: false,
    //       maxLength: '',
    //       inputType: '',
    //       labelPlacement: '',
    //       descriptionPlacement: '',
    //       subLabelPlacement: '',
    //       placeholder: 'Enter Your Name',
    //       cssClass: '',
    //       inputName: '',
    //       noDuplicates: false,
    //       defaultValue: '',
    //       enableAutocomplete: false,
    //       autocompleteAttribute: '',
    //       choices: '',
    //       conditionalLogic: '',
    //       productField: '',
    //       layoutGridColumnSpan: '',
    //       enablePasswordInput: '',
    //       enableEnhancedUI: 0,
    //       layoutGroupId: '3e36c36e',
    //       multipleFiles: false,
    //       maxFiles: '',
    //       calculationFormula: '',
    //       calculationRounding: '',
    //       enableCalculation: '',
    //       disableQuantity: false,
    //       displayAllCategories: false,
    //       useRichTextEditor: false,
    //       errors: [],
    //       fields: '',
    //     },
    //     {
    //       type: 'radio',
    //       id: 3,
    //       formId: 8,
    //       label: 'Gender',
    //       adminLabel: '',
    //       isRequired: true,
    //       size: 'large',
    //       errorMessage: '',
    //       visibility: 'visible',
    //       validateState: true,
    //       inputs: null,
    //       choices: [
    //         {
    //           text: 'Male',
    //           value: 'Male',
    //           isSelected: false,
    //           price: '',
    //         },
    //         {
    //           text: 'Female',
    //           value: 'Female',
    //           isSelected: false,
    //           price: '',
    //         },
    //         {
    //           text: 'Others',
    //           value: 'Others',
    //           isSelected: false,
    //           price: '',
    //         },
    //       ],
    //       description: '',
    //       allowsPrepopulate: false,
    //       inputMask: false,
    //       inputMaskValue: '',
    //       inputMaskIsCustom: false,
    //       maxLength: '',
    //       inputType: '',
    //       labelPlacement: '',
    //       descriptionPlacement: '',
    //       subLabelPlacement: '',
    //       placeholder: '',
    //       cssClass: '',
    //       inputName: '',
    //       noDuplicates: false,
    //       defaultValue: '',
    //       enableAutocomplete: false,
    //       autocompleteAttribute: '',
    //       conditionalLogic: '',
    //       productField: '',
    //       layoutGridColumnSpan: '',
    //       enableOtherChoice: '',
    //       enablePrice: '',
    //       enableEnhancedUI: 0,
    //       layoutGroupId: 'e1393c43',
    //       multipleFiles: false,
    //       maxFiles: '',
    //       calculationFormula: '',
    //       calculationRounding: '',
    //       enableCalculation: '',
    //       disableQuantity: false,
    //       displayAllCategories: false,
    //       useRichTextEditor: false,
    //       errors: [],
    //       enableChoiceValue: true,
    //       fields: '',
    //     },
    //     {
    //       type: 'number',
    //       id: 4,
    //       formId: 8,
    //       label: 'Age',
    //       adminLabel: '',
    //       isRequired: false,
    //       size: 'large',
    //       errorMessage: '',
    //       visibility: 'visible',
    //       inputs: null,
    //       numberFormat: 'decimal_dot',
    //       description: '',
    //       allowsPrepopulate: false,
    //       inputMask: false,
    //       inputMaskValue: '',
    //       inputMaskIsCustom: false,
    //       maxLength: '',
    //       inputType: '',
    //       labelPlacement: '',
    //       descriptionPlacement: '',
    //       subLabelPlacement: '',
    //       placeholder: '',
    //       cssClass: '',
    //       inputName: '',
    //       noDuplicates: false,
    //       defaultValue: '',
    //       enableAutocomplete: false,
    //       autocompleteAttribute: '',
    //       choices: '',
    //       conditionalLogic: {
    //         enabled: true,
    //         actionType: 'show',
    //         logicType: 'all',
    //         rules: [
    //           {
    //             fieldId: '3',
    //             operator: 'is',
    //             value: 'Male',
    //           },
    //         ],
    //       },
    //       enableCalculation: false,
    //       rangeMin: '',
    //       rangeMax: '',
    //       calculationFormula: '',
    //       productField: '',
    //       layoutGridColumnSpan: '',
    //       enableEnhancedUI: 0,
    //       layoutGroupId: '91b797e6',
    //       multipleFiles: false,
    //       maxFiles: '',
    //       calculationRounding: '',
    //       disableQuantity: false,
    //       displayAllCategories: false,
    //       useRichTextEditor: false,
    //       errors: [],
    //       fields: '',
    //     },
    //   ],
    //   version: '2.6.7',
    //   id: 8,
    //   markupVersion: 2,
    //   nextFieldId: 5,
    //   useCurrentUserAsAuthor: true,
    //   postContentTemplateEnabled: false,
    //   postTitleTemplateEnabled: false,
    //   postTitleTemplate: '',
    //   postContentTemplate: '',
    //   lastPageButton: null,
    //   pagination: null,
    //   firstPageCssClass: null,
    //   confirmations: [
    //     {
    //       id: '6343fbb60cdca',
    //       name: 'Default Confirmation',
    //       isDefault: true,
    //       type: 'message',
    //       message:
    //         'Thanks for contacting us! We will get in touch with you shortly.',
    //       url: '',
    //       pageId: '',
    //       queryString: '',
    //     },
    //   ],
    //   notifications: [
    //     {
    //       id: '6343fbb60cb2c',
    //       isActive: true,
    //       to: '{admin_email}',
    //       name: 'Admin Notification',
    //       event: 'form_submission',
    //       toType: 'email',
    //       subject: 'New submission from {form_title}',
    //       message: '{all_fields}',
    //     },
    //   ],
    // };

    {
      '0': {
        title: 'Ashu Form',
        description: '',
        labelPlacement: 'top_label',
        descriptionPlacement: 'below',
        button: {
          type: 'text',
          text: 'Submit',
          imageUrl: '',
          width: 'auto',
          location: 'bottom',
          layoutGridColumnSpan: 12,
          id: 'submit',
        },
        fields: [
          {
            type: 'text',
            id: 1,
            formId: 8,
            label: 'name',
            adminLabel: '',
            isRequired: false,
            size: 'large',
            errorMessage: '',
            visibility: 'visible',
            inputs: null,
            description: '',
            allowsPrepopulate: false,
            inputMask: false,
            inputMaskValue: '',
            inputMaskIsCustom: false,
            maxLength: '',
            inputType: '',
            labelPlacement: '',
            descriptionPlacement: '',
            subLabelPlacement: '',
            placeholder: 'Enter Your Name',
            cssClass: '',
            inputName: '',
            noDuplicates: false,
            defaultValue: '',
            enableAutocomplete: false,
            autocompleteAttribute: '',
            choices: '',
            conditionalLogic: '',
            productField: '',
            layoutGridColumnSpan: 3,
            enablePasswordInput: '',
            enableEnhancedUI: 0,
            layoutGroupId: '3e36c36e',
            multipleFiles: false,
            maxFiles: '',
            calculationFormula: '',
            calculationRounding: '',
            enableCalculation: '',
            disableQuantity: false,
            displayAllCategories: false,
            useRichTextEditor: false,
            errors: [],
            fields: '',
            displayOnly: '',
          },
          {
            type: 'text',
            id: 5,
            formId: 8,
            label: 'surename',
            adminLabel: '',
            isRequired: false,
            size: 'large',
            errorMessage: '',
            visibility: 'visible',
            inputs: null,
            description: '',
            allowsPrepopulate: false,
            inputMask: false,
            inputMaskValue: '',
            inputMaskIsCustom: false,
            maxLength: '',
            inputType: '',
            labelPlacement: '',
            descriptionPlacement: '',
            subLabelPlacement: '',
            placeholder: '',
            cssClass: '',
            inputName: '',
            noDuplicates: false,
            defaultValue: '',
            enableAutocomplete: false,
            autocompleteAttribute: '',
            choices: '',
            conditionalLogic: '',
            productField: '',
            layoutGridColumnSpan: 3,
            enablePasswordInput: '',
            enableEnhancedUI: 0,
            layoutGroupId: '3e36c36e',
            multipleFiles: false,
            maxFiles: '',
            calculationFormula: '',
            calculationRounding: '',
            enableCalculation: '',
            disableQuantity: false,
            displayAllCategories: false,
            useRichTextEditor: false,
            errors: [],
            fields: '',
            displayOnly: '',
          },
          {
            type: 'text',
            id: 6,
            formId: 8,
            label: 'Mother Name',
            adminLabel: '',
            isRequired: false,
            size: 'large',
            errorMessage: '',
            visibility: 'visible',
            inputs: null,
            description: '',
            allowsPrepopulate: false,
            inputMask: false,
            inputMaskValue: '',
            inputMaskIsCustom: '',
            maxLength: '',
            inputType: '',
            labelPlacement: '',
            descriptionPlacement: '',
            subLabelPlacement: '',
            placeholder: '',
            cssClass: '',
            inputName: '',
            noDuplicates: false,
            defaultValue: '',
            enableAutocomplete: false,
            autocompleteAttribute: '',
            choices: '',
            conditionalLogic: '',
            productField: '',
            layoutGridColumnSpan: 3,
            enablePasswordInput: '',
            enableEnhancedUI: 0,
            layoutGroupId: '3e36c36e',
            fields: '',
          },
          {
            type: 'text',
            id: 7,
            formId: 8,
            label: 'Father Name',
            adminLabel: '',
            isRequired: false,
            size: 'large',
            errorMessage: '',
            visibility: 'visible',
            inputs: null,
            description: '',
            allowsPrepopulate: false,
            inputMask: false,
            inputMaskValue: '',
            inputMaskIsCustom: '',
            maxLength: '',
            inputType: '',
            labelPlacement: '',
            descriptionPlacement: '',
            subLabelPlacement: '',
            placeholder: '',
            cssClass: '',
            inputName: '',
            noDuplicates: false,
            defaultValue: '',
            enableAutocomplete: false,
            autocompleteAttribute: '',
            choices: '',
            conditionalLogic: '',
            productField: '',
            layoutGridColumnSpan: 3,
            enablePasswordInput: '',
            enableEnhancedUI: 0,
            layoutGroupId: '3e36c36e',
            fields: '',
          },
          {
            type: 'radio',
            id: 3,
            formId: 8,
            label: 'Gender',
            adminLabel: '',
            isRequired: true,
            size: 'large',
            errorMessage: '',
            visibility: 'visible',
            validateState: true,
            inputs: null,
            choices: [
              {
                text: 'Male',
                value: 'Male',
                isSelected: false,
                price: '',
              },
              {
                text: 'Female',
                value: 'Female',
                isSelected: false,
                price: '',
              },
              {
                text: 'Others',
                value: 'Others',
                isSelected: false,
                price: '',
              },
            ],
            description: '',
            allowsPrepopulate: false,
            inputMask: false,
            inputMaskValue: '',
            inputMaskIsCustom: false,
            maxLength: '',
            inputType: '',
            labelPlacement: '',
            descriptionPlacement: '',
            subLabelPlacement: '',
            placeholder: '',
            cssClass: '',
            inputName: '',
            noDuplicates: false,
            defaultValue: '',
            enableAutocomplete: false,
            autocompleteAttribute: '',
            conditionalLogic: '',
            productField: '',
            layoutGridColumnSpan: 12,
            enableOtherChoice: '',
            enablePrice: '',
            enableEnhancedUI: 0,
            layoutGroupId: 'e1393c43',
            multipleFiles: false,
            maxFiles: '',
            calculationFormula: '',
            calculationRounding: '',
            enableCalculation: '',
            disableQuantity: false,
            displayAllCategories: false,
            useRichTextEditor: false,
            errors: [],
            enableChoiceValue: true,
            fields: '',
            displayOnly: '',
          },
          {
            type: 'number',
            id: 4,
            formId: 8,
            label: 'Age',
            adminLabel: '',
            isRequired: false,
            size: 'large',
            errorMessage: '',
            visibility: 'visible',
            inputs: null,
            numberFormat: 'decimal_dot',
            description: '',
            allowsPrepopulate: false,
            inputMask: false,
            inputMaskValue: '',
            inputMaskIsCustom: false,
            maxLength: '',
            inputType: '',
            labelPlacement: '',
            descriptionPlacement: '',
            subLabelPlacement: '',
            placeholder: '',
            cssClass: '',
            inputName: '',
            noDuplicates: false,
            defaultValue: '',
            enableAutocomplete: false,
            autocompleteAttribute: '',
            choices: '',
            conditionalLogic: '',
            enableCalculation: false,
            rangeMin: '',
            rangeMax: '',
            calculationFormula: '',
            productField: '',
            layoutGridColumnSpan: '',
            enableEnhancedUI: 0,
            layoutGroupId: '91b797e6',
            multipleFiles: false,
            maxFiles: '',
            calculationRounding: '',
            disableQuantity: false,
            displayAllCategories: false,
            useRichTextEditor: false,
            errors: [],
            fields: '',
            displayOnly: '',
          },
        ],
        version: '2.6.7',
        id: 8,
        markupVersion: 2,
        nextFieldId: 8,
        useCurrentUserAsAuthor: true,
        postContentTemplateEnabled: false,
        postTitleTemplateEnabled: false,
        postTitleTemplate: '',
        postContentTemplate: '',
        lastPageButton: null,
        pagination: null,
        firstPageCssClass: null,
        confirmations: [
          {
            id: '6343fbb60cdca',
            name: 'Default Confirmation',
            isDefault: true,
            type: 'message',
            message:
              'Thanks for contacting us! We will get in touch with you shortly.',
            url: '',
            pageId: '',
            queryString: '',
          },
        ],
        notifications: [
          {
            id: '6343fbb60cb2c',
            isActive: true,
            to: '{admin_email}',
            name: 'Admin Notification',
            event: 'form_submission',
            toType: 'email',
            subject: 'New submission from {form_title}',
            message: '{all_fields}',
          },
        ],
      },
      version: '2.6.7',
    };
  // Formfields: any[] = [
  //   {
  //     type: 'text',
  //     name: 'firstName',
  //     label: 'First Name',
  //     placeholder: 'Enter First Name',
  //     value: '',
  //     required: true,
  //   },
  //   {
  //     type: 'text',
  //     name: 'lastName',
  //     label: 'Last Name',
  //     placeholder: 'Enter Last Name',
  //     value: '',
  //     required: true,
  //   },
  //   {
  //     type: 'text',
  //     name: 'email',
  //     label: 'Email',
  //     placeholder: 'Enter Email',
  //     value: '',
  //     required: true,
  //   },
  //   {
  //     type: 'dropdown',
  //     name: 'country',
  //     label: 'Country',
  //     // value: 'in',
  //     required: true,
  //     options: [
  //       { key: 'in', label: 'India' },
  //       { key: 'us', label: 'USA' },
  //     ],
  //   },
  //   {
  //     type: 'radio',
  //     name: 'gender',
  //     label: 'Gender',
  //     // value: '',
  //     required: true,
  //     options: [
  //       { key: 'm', label: 'Male' },
  //       { key: 'f', label: 'Female' },
  //     ],
  //     selectValue: [
  //       {
  //         value: 'm',
  //         lable: 'mr',
  //       },
  //       {
  //         value: 'f',
  //         lable: 'mis',
  //       },
  //     ],
  //   },
  //   {
  //     type: 'checkbox',
  //     name: 'hobby',
  //     label: 'Hobby',
  //     required: true,
  //     options: [
  //       { key: 'f', label: 'Fishing' },
  //       { key: 'c', label: 'Cooking' },
  //     ],
  //   },
  // ];

  selectedvalue: any;
  mrmiss: any;
  constructor(
    private route: ActivatedRoute,
    private sanitizer: DomSanitizer,
    private FormBuilder: FormBuilder
  ) {
    let group: any = {};
    this.FormData[0].fields.forEach((res: any) => {
      console.log(res.type);
      group[res.label] = new FormControl('');
    });
    this.myForm = new FormGroup(group);
  }
  // url = 'http://127.0.0.1:5502/index.html';
  // defurl: any;
  ngOnInit() {
    console.log('formFields', this.FormData[0]);
    console.log(this.myForm.controls);
    // this.FormData[0].forEach((res: any) => {
    //   // console.log(res.selectValue);
    //   // this.selectedvalue = res.selectValue;
    //   console.log(res);
    // });
    //   console.log('this selected value', this.selectedvalue);
  }

  dataSubmit() {
    console.log(this.myForm.value);
  }
  onChangeradion(selectValue: any) {
    console.log('selectValue', selectValue);
    this.selectedvalue = selectValue;
  }
  changeselection() {
    // console.log('Gender Selection', selectedgender);
    // for (let i = 0; i < selecteValue.length; i++) {
    //   if (selecteValue[i].value == selectedgender) {
    //     this.mrmiss = selecteValue[i].lable;
    //     console.log(this.mrmiss);
    //   }
    // }
  }
  get f() {
    return this.myForm.controls;
  }
}
