import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { Router } from '@angular/router';

@Component({
  selector: 'app-employee',
  templateUrl: './employee.component.html',
  styleUrls: ['./employee.component.scss'],
})
export class EmployeeComponent implements OnInit {
  jsonFrom: any = {
    '0': {
      title: 'Demo All Fields',
      description: 'Form',
      labelPlacement: 'top_label',
      descriptionPlacement: 'below',
      button: {
        type: 'text',
        text: 'Submit',
        imageUrl: '',
        width: 'auto',
        location: 'bottom',
        layoutGridColumnSpan: 12,
      },
      fields: [
        {
          type: 'text',
          id: 1,
          formId: 7,
          label: 'Name',
          adminLabel: '',
          isRequired: true,
          size: 'large',
          errorMessage: '',
          visibility: 'visible',
          inputs: null,
          description: '',
          allowsPrepopulate: false,
          inputMask: false,
          inputMaskValue: '',
          inputMaskIsCustom: false,
          maxLength: '',
          inputType: '',
          labelPlacement: '',
          descriptionPlacement: '',
          subLabelPlacement: '',
          placeholder: 'Enter Your Name',
          cssClass: '',
          inputName: '',
          noDuplicates: false,
          defaultValue: '',
          enableAutocomplete: false,
          autocompleteAttribute: '',
          choices: '',
          conditionalLogic: '',
          productField: '',
          layoutGridColumnSpan: '',
          enablePasswordInput: '',
          enableEnhancedUI: 0,
          layoutGroupId: '9458c27f',
          multipleFiles: false,
          maxFiles: '',
          calculationFormula: '',
          calculationRounding: '',
          enableCalculation: '',
          disableQuantity: false,
          displayAllCategories: false,
          useRichTextEditor: false,
          errors: [],
          fields: '',
          displayOnly: '',
        },
        {
          type: 'select',
          id: 3,
          formId: 7,
          label: 'Country',
          adminLabel: '',
          isRequired: true,
          size: 'large',
          errorMessage: '',
          visibility: 'visible',
          inputs: null,
          choices: [
            {
              text: 'India',
              value: 'India',
              isSelected: false,
              price: '',
            },
            {
              text: 'USA',
              value: 'USA',
              isSelected: false,
              price: '',
            },
            {
              text: 'Cannada',
              value: 'Canada',
              isSelected: false,
              price: '',
            },
          ],
          description: '',
          allowsPrepopulate: false,
          inputMask: false,
          inputMaskValue: '',
          inputMaskIsCustom: false,
          maxLength: '',
          inputType: '',
          labelPlacement: '',
          descriptionPlacement: '',
          subLabelPlacement: '',
          placeholder: '',
          cssClass: '',
          inputName: '',
          noDuplicates: false,
          defaultValue: '',
          enableAutocomplete: false,
          autocompleteAttribute: '',
          conditionalLogic: '',
          productField: '',
          layoutGridColumnSpan: '',
          enablePrice: '',
          enableEnhancedUI: 0,
          layoutGroupId: '989f44a4',
          multipleFiles: false,
          maxFiles: '',
          calculationFormula: '',
          calculationRounding: '',
          enableCalculation: '',
          disableQuantity: false,
          displayAllCategories: false,
          useRichTextEditor: false,
          errors: [],
          enableChoiceValue: true,
          fields: '',
          displayOnly: '',
        },
        {
          type: 'number',
          id: 4,
          formId: 7,
          label: 'Mobile Number',
          adminLabel: '',
          isRequired: true,
          size: 'large',
          errorMessage: '',
          visibility: 'visible',
          inputs: null,
          numberFormat: 'decimal_dot',
          description: '',
          allowsPrepopulate: false,
          inputMask: false,
          inputMaskValue: '',
          inputMaskIsCustom: false,
          maxLength: '',
          inputType: '',
          labelPlacement: '',
          descriptionPlacement: '',
          subLabelPlacement: '',
          placeholder: '',
          cssClass: '',
          inputName: '',
          noDuplicates: false,
          defaultValue: '',
          enableAutocomplete: false,
          autocompleteAttribute: '',
          choices: '',
          conditionalLogic: '',
          enableCalculation: false,
          rangeMin: '',
          rangeMax: '',
          calculationFormula: '',
          productField: '',
          layoutGridColumnSpan: '',
          enableEnhancedUI: 0,
          layoutGroupId: 'bfa88645',
          multipleFiles: false,
          maxFiles: '',
          calculationRounding: '',
          disableQuantity: false,
          displayAllCategories: false,
          useRichTextEditor: false,
          errors: [],
          fields: '',
          displayOnly: '',
        },
        {
          type: 'checkbox',
          id: 5,
          formId: 7,
          label: 'Hoby',
          adminLabel: '',
          isRequired: true,
          size: 'large',
          errorMessage: '',
          visibility: 'visible',
          choices: [
            {
              text: 'Playing FootBal',
              value: 'Playing FootBal',
              isSelected: false,
              price: '',
            },
            {
              text: 'Music',
              value: 'Music',
              isSelected: false,
              price: '',
            },
            {
              text: 'Online Gaming',
              value: 'Online Gaming',
              isSelected: false,
              price: '',
            },
          ],
          inputs: [
            {
              id: '5.1',
              label: 'Playing FootBal',
              name: '',
            },
            {
              id: '5.2',
              label: 'Music',
              name: '',
            },
            {
              id: '5.3',
              label: 'Online Gaming',
              name: '',
            },
          ],
          description: '',
          allowsPrepopulate: false,
          inputMask: false,
          inputMaskValue: '',
          inputMaskIsCustom: false,
          maxLength: '',
          inputType: '',
          labelPlacement: '',
          descriptionPlacement: '',
          subLabelPlacement: '',
          placeholder: '',
          cssClass: '',
          inputName: '',
          noDuplicates: false,
          defaultValue: '',
          enableAutocomplete: false,
          autocompleteAttribute: '',
          conditionalLogic: '',
          productField: '',
          layoutGridColumnSpan: '',
          enableSelectAll: false,
          enablePrice: '',
          enableEnhancedUI: 0,
          layoutGroupId: 'ca792cdb',
          multipleFiles: false,
          maxFiles: '',
          calculationFormula: '',
          calculationRounding: '',
          enableCalculation: '',
          disableQuantity: false,
          displayAllCategories: false,
          useRichTextEditor: false,
          errors: [],
          checkboxLabel: '',
          enableChoiceValue: true,
          fields: '',
          displayOnly: '',
        },
        {
          type: 'radio',
          id: 6,
          formId: 7,
          label: 'Gender',
          adminLabel: '',
          isRequired: true,
          size: 'large',
          errorMessage: '',
          visibility: 'visible',
          validateState: true,
          inputs: null,
          choices: [
            {
              text: 'Male',
              value: 'Male',
              isSelected: false,
              price: '',
            },
            {
              text: 'Female',
              value: 'Female',
              isSelected: false,
              price: '',
            },
            {
              text: 'Other',
              value: 'Other',
              isSelected: false,
              price: '',
            },
          ],
          description: '',
          allowsPrepopulate: false,
          inputMask: false,
          inputMaskValue: '',
          inputMaskIsCustom: false,
          maxLength: '',
          inputType: '',
          labelPlacement: '',
          descriptionPlacement: '',
          subLabelPlacement: '',
          placeholder: '',
          cssClass: '',
          inputName: '',
          noDuplicates: false,
          defaultValue: '',
          enableAutocomplete: false,
          autocompleteAttribute: '',
          conditionalLogic: '',
          productField: '',
          layoutGridColumnSpan: '',
          enableOtherChoice: '',
          enablePrice: '',
          enableEnhancedUI: 0,
          layoutGroupId: '226be625',
          multipleFiles: false,
          maxFiles: '',
          calculationFormula: '',
          calculationRounding: '',
          enableCalculation: '',
          disableQuantity: false,
          displayAllCategories: false,
          useRichTextEditor: false,
          errors: [],
          enableChoiceValue: true,
          fields: '',
          displayOnly: '',
        },
      ],
      version: '2.6.7',
      id: 7,
      markupVersion: 2,
      nextFieldId: 7,
      useCurrentUserAsAuthor: true,
      postContentTemplateEnabled: false,
      postTitleTemplateEnabled: false,
      postTitleTemplate: '',
      postContentTemplate: '',
      lastPageButton: null,
      pagination: null,
      firstPageCssClass: null,
      confirmations: [
        {
          id: '6343ba97754bd',
          name: 'Default Confirmation',
          isDefault: true,
          type: 'message',
          message:
            'Thanks for contacting us! We will get in touch with you shortly.',
          url: '',
          pageId: '',
          queryString: '',
        },
      ],
      notifications: [
        {
          id: '6343ba97752a0',
          isActive: true,
          to: '{admin_email}',
          name: 'Admin Notification',
          event: 'form_submission',
          toType: 'email',
          subject: 'New submission from {form_title}',
          message: '{all_fields}',
        },
      ],
    },
    version: '2.6.7',
  };
  
  leaveForm: FormGroup;
  leaverequest: any = [];
  grouptext: any = {
    name: 'ashu',
    pandey: 'pandey',
  };
  selctValue: any;
  rules: any = [];

  constructor(private FormBuilder: FormBuilder, private Route: Router) {
    this.leaveForm = this.FormBuilder.group({
      nameEmployee: [''],
      purposeLeave: [''],
      dateLeave: [''],
    });
  }

  ngOnInit(): void {
    this.jsonFrom[0].fields.forEach((res: any) => {
      this.rules = res.conditionalLogic.rules;
      console.log('rules', this.rules);
      console.log('resss', res.conditionalLogic.rules);
    });
  }
  onChangeradion(selectValue: any) {
    this.selctValue = selectValue;
    console.log('selectValue', this.selctValue);
  }

  async leaveSub() {
    console.log(this.leaveForm.value);
    await this.leaverequest.push(this.leaveForm.value);
    console.log('leaverequest', this.leaverequest);
    this.Route.navigate(['/hr'], { queryParams: this.grouptext });
  }
}
